
using System.IO;
using Generator.Context;
using Generator.Kind;
using Generator.Util;
using Generator.Visitor;

namespace Generator.Edb
{
    public class XBeanGenerator : BaseGenerator<XBeanNamespaceKind>
    {
        public XBeanGenerator(GloableContext gc) : 
            base(gc, new GeneratorContext(), Files.XBeanPath)
        {
        }

        protected override void Generate0()
        {
            foreach (var namespaceClassKind in NamespaceClassKinds())
            {
                var identiferKinds = namespaceClassKind.Value;
                foreach (var identiferKind in identiferKinds)
                {
                    var beanKind = (XBeanClassKind)identiferKind;
                    try
                    {
                        GenerateBean(beanKind);
                    } catch (System.Exception e)
                    {
                        throw new System.Exception($"生成XBean {beanKind.Name}失败", e);
                    }
                }
            }
        }
        
        private void GenerateBean(XBeanClassKind beanKind)
        {
            var fieldsLine = new Writer(true, 2);
            var getterLine = new Writer(true, 2);
            foreach (var fieldKind in beanKind.Children())
            {
                // 字段定义
                var defineVisitor = new EdbFullNameTypeVisitor();
                fieldKind.Type.Accept(defineVisitor);
                fieldsLine.WriteLine($"private {defineVisitor.Result} {fieldKind.Name};");
                
                // getter 生成
                if (beanKind.IdFieldName == fieldKind.Name) // bson id特性生成
                    getterLine.WriteLine("[MongoDB.Bson.Serialization.Attributes.BsonId]");
                var getterVisitor = new XBeanFieldGetterTypeVisitor(beanKind, (XBeanFieldKind)fieldKind);
                fieldKind.Type.Accept(getterVisitor);
                getterLine.WriteLine($"{getterVisitor.Result}");
            }
            
            var filePath = Path.Combine(OutPath, $"{beanKind.Name}{Files.CodeFileSuffix}");
            var code = $@"
{AutoGenerated}
namespace XBean
{{
    public class {beanKind.Name} : Edb.XBean
    {{
        {fieldsLine}

        protected {beanKind.Name}(Edb.XBean? _xp_, string _vn_) : base(_xp_, _vn_)
        {{
        }}

        public {beanKind.Name}() : this(null, null!)
        {{
        }}

        public {beanKind.Name}({beanKind.Name} _o_) : this(_o_, null, null!)
        {{
        }}

        protected {beanKind.Name}({beanKind.Name} _o_, Edb.XBean? _xp_, string _vn_) : base(_xp_, _vn_)
        {{
            _o_.VerifyStandaloneOrLockHeld(""_o_.{beanKind.Name}"", true);
        }}

        public void CopyFrom({beanKind.Name} _o_)
        {{
            _o_.VerifyStandaloneOrLockHeld(""CopyFrom{beanKind.Name}"", true);
            VerifyStandaloneOrLockHeld(""CopyTo{beanKind.Name}"", false);
        }}
        
        {getterLine}
    }}
}}
";
            Gc.Log($"生成文件: {filePath}");
            File.WriteAllText(filePath, code);
        }
    }
}